name: Trigger auto deployment for admin

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/admin-AutoDeployTrigger-34fd73c6-8ed2-4f53-bfc7-fbfba4de14f1.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ADMIN_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ADMIN_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ADMIN_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: acr3c4cn3rgwaqwk.azurecr.io
          registryUsername: ${{ secrets.ADMIN_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ADMIN_REGISTRY_PASSWORD }}
          containerAppName: admin
          resourceGroup: rg-AzUrlShortener
          imageToBuild: acr3c4cn3rgwaqwk.azurecr.io/admin:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


